
import os
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"
print "This is very cool"

